version: 1.0.0.{build}

pull_requests:
  do_not_increment_build_number: true

branches:
  only:
  - master

nuget:
  disable_publish_on_pr: true
  account_feed: false
  project_feed: true

image: Visual Studio 2017

environment:
  docspush_email: 32618965+cibuild-telliam@users.noreply.github.com
  docspush_username: cibuild-telliam
  docspush_access_token:
    secure: QqWCIyFM6uBBbkW1jnlVGsMQWy+9aPY9rhD56oNT2L/0Cmw2bynROEsrUrOPpBrk

skip_commits:
  files:
    - '**\*.md'

init:
  - git config --global core.safecrlf false
  - git config --global core.autocrlf input

configuration: Release

before_build:
  - cmd: msbuild /t:Restore CommandlineParsing.sln
  - ps: Clone-Docs.ps1

build:
  project: CommandlineParsing.sln
  verbosity: minimal

artifacts:
  - path: BuildOutput\NuGet\*.nupkg

deploy_script:
  - ps: .\Push-Docs.ps1
