name: CI Build

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check Out
      uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json
    - name: Build with PowerShell
      shell: pwsh
      run: .\Build-All.ps1 -Configuration Release -ForceClean
